"""added is_pinned to tasks

Revision ID: 6218c3b53b9f
Revises: 9b85f5430351
Create Date: 2025-12-28 04:43:28.924327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6218c3b53b9f'
down_revision: Union[str, None] = '9b85f5430351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_pinned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_pinned')
    # ### end Alembic commands ###
